import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// @req FR-FLOW-124  the full cycle is the default; --none-cycle is the single opt-out
// @req FR-FLOW-125  contradictory option combinations are refused at entry
// @req FR-FLOW-126  the work-mode routing exclusion is keyed on delegated wave entry
// @req FR-FLOW-127  every gate keyed on the cycle flag is re-keyed on its real condition
// @req FR-FLOW-128  no rendering keeps a safety claim the flip makes false
// @req FR-FLOW-129  the orchestrator refusal and the shared contract are re-keyed
// @req FR-FLOW-039  the work-mode router stays reachable — its previous evidence was whole-body
//                   token presence, which stays green while the gate can never fire

//
// A SKILL.md is natural-language agent instruction, so these are raw-text contract assertions.
// Two properties this change makes load-bearing, both learned from mutations that survived here
// before:
//
//   - Scope to the section or table ROW under test. `--cycle` appears in eight sections of the
//     pipeline body, so a whole-document search is satisfied by a section unrelated to the rule.
//     The gate table is the SSOT an --auto agent reads; a re-arm stated in the prose below it does
//     not reach that reader.
//   - Assert the RE-ARM, never the exemption's spelling. A universal exemption re-spelled in new
//     wording ("`--none-cycle` 미지정 시 비적용") evades every negative assertion and satisfies none
//     of the positive ones.
//
// Renderings: kiwi-pipeline, kiwi-orchestrator and the shared contract ship in four copies each
// (claude / codex / etc plus the `.agents` mirror, regenerated by `speckiwi skills mirror --write`
// and never hand-edited). kiwi-wave-master ships in three — `.agents` excludes it deliberately as a
// hermeticity leak sentinel, and that asymmetry is asserted rather than closed.

const REPO_ROOT = fileURLToPath(new URL("../../", import.meta.url));

function copies(skill: string): string[] {
  return [
    `skills/claude/${skill}/SKILL.md`,
    `skills/codex/${skill}/SKILL.md`,
    `skills/etc/${skill}/SKILL.md`,
    `.agents/skills/${skill}/SKILL.md`
  ];
}

const PIPELINE_COPIES = copies("kiwi-pipeline");
const ORCHESTRATOR_COPIES = copies("kiwi-orchestrator");
const CONTRACT_COPIES = [
  "skills/claude/_shared/kiwi/pipeline-v1.md",
  "skills/codex/_shared/kiwi/pipeline-v1.md",
  "skills/etc/_shared/kiwi/pipeline-v1.md",
  ".agents/skills/_shared/kiwi/pipeline-v1.md"
];
/** Three, not four: the mirror excludes kiwi-wave-master by design. */
const WAVE_COPIES = ["claude", "codex", "etc"].map((v) => `skills/${v}/kiwi-wave-master/SKILL.md`);

function read(relPath: string): string {
  return readFileSync(path.join(REPO_ROOT, relPath), "utf8");
}

/** Body with the YAML frontmatter stripped, so `description` cannot false-green a body check. */
function body(text: string): string {
  return text.replace(/^---[\s\S]*?\n---\s*\n?/, "");
}

/** The frontmatter `description` field alone — the routing surface, asserted separately. */
function description(text: string): string {
  const fm = /^---([\s\S]*?)\n---/.exec(text);
  return fm ? fm[1] : "";
}

/** A heading and everything under it, down to the next same-or-higher-level heading. "" when absent. */
function section(text: string, headingRe: RegExp): string {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => /^#{1,6}\s/.test(l) && headingRe.test(l));
  if (start === -1) return "";
  const level = (lines[start].match(/^#+/) as RegExpMatchArray)[0].length;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    const m = lines[i].match(/^#+/);
    if (m && m[0].length <= level) {
      end = i;
      break;
    }
  }
  return lines.slice(start, end).join("\n");
}

/** The single line containing the first match of `re`. "" when absent. */
function line(text: string, re: RegExp): string {
  return text.split("\n").find((l) => re.test(l)) ?? "";
}

/** Every line matching `re`. Used where "exactly one place" is the rule. */
function lines(text: string, re: RegExp): string[] {
  return text.split("\n").filter((l) => re.test(l));
}

/** Trimmed cells of the first table row matching `re`; [] when absent. */
function rowCells(text: string, re: RegExp): string[] {
  const row = text.split("\n").find((l) => /^\s*\|/.test(l) && re.test(l));
  return row ? row.split("|").map((c) => c.trim()) : [];
}

/** Hedges that turn a MUST into a SHOULD; every prohibition asserts its own sentence carries none. */
const HEDGE = /수 있다|해도 된다|권장|바람직|원칙적으로|원칙으로 하되|가능하면|되도록|경우에 따라|가급적/;

/** §0 is a single table; its rows are addressed by key rather than by a heading of their own. */
const matrixOf = (t: string) => section(body(t), /^#{3}\s*1\.2\s/);
const gatesOf = (t: string) => section(body(t), /^#{3,4}\s.*critical_gates/i);
const cycleOf = (t: string) => section(body(t), /^#{2}\s*2\.5\s/);
const routingOf = (t: string) => section(body(t), /^#{2}\s*2\.8\s/);
const emitOf = (t: string) => section(body(t), /^#{3}\s*8\.2\s/);
const examplesOf = (t: string) => section(body(t), /^#{2}\s*11\.\s/);

describe.each(PIPELINE_COPIES)("FR-FLOW-124 — the cycle is the default (%s)", (copy) => {
  it("AC-1: §1.2 opens by naming the full cycle as the default and --none-cycle as the opt-out", () => {
    const headline = line(matrixOf(read(copy)), /기본 동작/);
    expect(headline, `${copy}: §1.2 must open with the default-behaviour sentence`).not.toBe("");
    expect(/사이클|§2\.5/.test(headline), `${copy}: the sentence must name the cycle`).toBe(true);
    expect(/--none-cycle/.test(headline), `${copy}: the sentence must name the opt-out`).toBe(true);
  });

  it("AC-2: §1.2 carries a --none-cycle row naming the restored single-next-step behaviour", () => {
    const cells = rowCells(matrixOf(read(copy)), /--none-cycle/);
    expect(cells.length, `${copy}: --none-cycle must be a first-class §1.2 row`).toBeGreaterThan(2);
    expect(
      /단일|다음-단계|다음 단계/.test(cells.join(" ")),
      `${copy}: the row must name what --none-cycle restores`
    ).toBe(true);
  });

  it("AC-3: the implicit run is no longer keyed on cycle entry", () => {
    const text = body(read(copy));
    expect(
      /`--cycle` 진입 \(`--run` 미지정\)/.test(text),
      `${copy}: keyed on cycle entry this now means every invocation spawns`
    ).toBe(false);
    const cond = line(matrixOf(read(copy)), /작업 입력/);
    expect(cond, `${copy}: the implicit run must be stated as conditional on a work input`).not.toBe("");
  });

  it("AC-4: a closed work-input enumeration is stated, and --target alone is excluded from it", () => {
    const matrix = matrixOf(read(copy));
    const enumeration = line(matrix, /작업 입력은[^\n]*닫힌다|작업 입력\s*=/);
    expect(enumeration, `${copy}: the enumeration must be stated as closed`).not.toBe("");
    for (const token of ["--from=", "--req-filter", "--plan-run-id"]) {
      expect(enumeration.includes(token), `${copy}: the enumeration must list ${token}`).toBe(true);
    }
    const target = line(matrix, /`--target` 단독/);
    expect(target, `${copy}: --target alone must be addressed`).not.toBe("");
    expect(/아니다/.test(target), `${copy}: --target alone must be excluded from work input`).toBe(true);
    // `--run` asks for execution, not for a unit of work. Admitting it to the enumeration put
    // `/kiwi-pipeline --run` under two rules at once — "spawn one next step" (the matrix row that has
    // said so since before the flip) and "spawn the whole chain" — with nothing to break the tie.
    expect(
      /명시적 `--run`/.test(enumeration),
      `${copy}: --run in the work-input enumeration collides with the --run-alone matrix row`
    ).toBe(false);
    const runAlone = line(matrix, /`--run` 은 여기에/);
    expect(runAlone, `${copy}: --run alone must be told apart from a work input`).not.toBe("");
    expect(/한 단계/.test(runAlone), `${copy}: --run alone keeps its single-next-step meaning`).toBe(true);
  });

  it("AC-5: ambiguity resolves to no work input", () => {
    const tie = line(matrixOf(read(copy)), /갈리면|모호하면/);
    expect(tie, `${copy}: an ambiguity tie-breaker must be stated`).not.toBe("");
    expect(/작업 입력 없음/.test(tie), `${copy}: ambiguity must resolve to no work input`).toBe(true);
  });

  it("AC-6: --cycle is declared inert in exactly one place, with the lagging-copy reason", () => {
    const text = body(read(copy));
    const declarations = lines(text, /`--cycle`[^\n]*inert/);
    expect(declarations.length, `${copy}: exactly one inert declaration, not ${declarations.length}`).toBe(1);
    expect(
      /뒤처지|lag/.test(declarations[0]),
      `${copy}: the reason a parsed-but-inert token is kept must be given`
    ).toBe(true);
    // Counting LINES misses a paragraph pasted twice inside one line — which is exactly how the
    // botched-edit signature relocated out of §8.2 and into here. Count occurrences, not lines.
    const intent = "동작이 없다는 것과 의도가 없다는 것은 다르다";
    expect(text.split(intent).length - 1, `${copy}: the intent clause must appear once`).toBeLessThanOrEqual(1);
  });

  it("AC-1 (non-auto authority): a work-input run without --auto still states who authorises each stage", () => {
    // The --auto half was re-keyed; the non-auto half is the more common invocation and was left
    // between two rules that say opposite things — confirm each hop, and spawn the next hop.
    const six1 = section(body(read(copy)), /^#{3}\s*6\.1\s/);
    expect(six1, `${copy}: §6.1 must exist`).not.toBe("");
    const rule = line(six1, /작업 입력을 실은 진입/);
    expect(rule, `${copy}: §6.1 must say what an implicit-run entry does about the per-hop gate`).not.toBe("");
    expect(
      /`--auto` 미지정|--auto 가 없으면/.test(rule),
      `${copy}: the implicit run must say whether the non-auto user gate still applies between stages`
    ).toBe(true);
  });
});

describe.each(PIPELINE_COPIES)("FR-FLOW-125 — contradictory combinations refused (%s)", (copy) => {
  it("AC-1: --none-cycle with a cycle-presupposing argument is refused at entry", () => {
    const refusal = line(matrixOf(read(copy)), /진입 시점에 거부/);
    expect(refusal, `${copy}: the refusal must be stated`).not.toBe("");
    for (const token of ["--cycle", "--from=", "--wt"]) {
      expect(refusal.includes(token), `${copy}: the refusal must name ${token}`).toBe(true);
    }
    expect(
      /우선순위로 해소하지 않는다/.test(refusal),
      `${copy}: precedence resolution must be excluded explicitly, not merely unmentioned`
    ).toBe(true);
    expect(HEDGE.test(refusal), `${copy}: the refusal must be absolute`).toBe(false);
  });

  it("AC-2: --stats implies --none-cycle, stated once, with the two axes distinguished", () => {
    const implications = lines(body(read(copy)), /`--stats`[^\n]*`--none-cycle`[^\n]*함의/);
    expect(implications.length, `${copy}: exactly one --stats implication line`).toBe(1);
    expect(
      /도는가/.test(implications[0]) && /출력/.test(implications[0]),
      `${copy}: the run-or-not axis and the what-to-print axis must be told apart by name`
    ).toBe(true);
  });

  it("AC-3: --no-cycle is refused by name rather than silently ignored", () => {
    const text = body(read(copy));
    const misspelling = line(text, /`--no-cycle`/);
    expect(misspelling, `${copy}: the --no-cycle spelling must be addressed`).not.toBe("");
    expect(
      /인식되지 않는|거부/.test(misspelling),
      `${copy}: a silently ignored opt-out runs the entire chain`
    ).toBe(true);
    expect(rowCells(matrixOf(read(copy)), /`--no-cycle`/).length, `${copy}: not a real flag row`).toBe(0);
  });

  it("AC-4: status phrasings reach the opt-out through the natural-language column", () => {
    const cells = rowCells(matrixOf(read(copy)), /--none-cycle/);
    const trigger = cells[1] ?? "";
    expect(
      /상태|status/.test(trigger),
      `${copy}: §1.2 is a trigger-phrase map — without a status row the opt-out is unreachable in Korean`
    ).toBe(true);
  });

  it("AC-5: the description states both the new default and the opt-out", () => {
    // The bodies are Korean in all three renderings; only the frontmatter legitimately differs in
    // language, so the default is keyed on either spelling of the same word.
    const desc = description(read(copy));
    expect(/사이클|cycle/i.test(desc), `${copy}: the routing surface must state the new default`).toBe(true);
    expect(/--none-cycle/.test(desc), `${copy}: the routing surface must state the opt-out`).toBe(true);
  });
});

describe.each(PIPELINE_COPIES)("FR-FLOW-126 — routing exclusion keyed on delegation (%s)", (copy) => {
  it("AC-1: the exclusion is no longer keyed on the cycle flag", () => {
    expect(
      /`--cycle` \/ `--from=` 진입은 본 라우팅의 적용 대상이 아니다/.test(routingOf(read(copy))),
      `${copy}: keyed on --cycle, this exclusion swallows every invocation and §2.8 never fires`
    ).toBe(false);
  });

  it("AC-2: the surviving exclusion names delegated entry, without hedging", () => {
    const rule = line(routingOf(read(copy)), /적용 대상이 아니다/);
    expect(rule, `${copy}: an exclusion must still exist`).not.toBe("");
    // NOT a disjunction that includes `--from=`: the pre-flip sentence contained `--from=` too, so
    // `/--from=|…/` is green on the text this requirement exists to remove. The discriminator is
    // the word for delegation itself, which the pre-flip sentence does not carry.
    expect(
      /위임 진입/.test(rule),
      `${copy}: the exclusion must key on delegated entry — the pre-flip sentence already contained --from=`
    ).toBe(true);
    expect(
      /부모 wave|orchestrator 가 spawn|body-scope/.test(rule),
      `${copy}: the exclusion must say what a delegated entry is`
    ).toBe(true);
    expect(HEDGE.test(rule), `${copy}: the exclusion must be absolute`).toBe(false);
  });

  it("AC-3: §2.8 states that running the default cycle alone does not exclude", () => {
    const alone = line(routingOf(read(copy)), /기본 사이클/);
    expect(alone, `${copy}: §2.8 must say what the default cycle alone does NOT do`).not.toBe("");
    expect(/만으로는|그 자체로는/.test(alone), `${copy}: the clause must be scoped to "alone"`).toBe(true);
    expect(/않는다|아니다/.test(alone), `${copy}: the clause must be negative`).toBe(true);
  });

  it("AC-4: a direct user invocation stays subject to the router", () => {
    const direct = line(routingOf(read(copy)), /직접 호출|사용자가 직접/);
    expect(direct, `${copy}: the case the router still governs must be named`).not.toBe("");
    expect(/적용된다|대상이다|그대로/.test(direct), `${copy}: it must stay subject, positively stated`).toBe(true);
  });

  it("AC-5: the two recorded reasons survive the restatement", () => {
    const routing = routingOf(read(copy));
    expect(/무인 완주/.test(routing), `${copy}: the always-HALT reason must survive`).toBe(true);
    expect(/증거 번들/.test(routing), `${copy}: the evidence-bundle reason must survive`).toBe(true);
  });
});

describe.each(PIPELINE_COPIES)("FR-FLOW-127 — gates re-keyed on their real condition (%s)", (copy) => {
  it("AC-1: the multi-candidate row names both the exempt case and the case it still fires", () => {
    const cells = rowCells(gatesOf(read(copy)), /multi-candidate-ambiguous/).join(" ");
    expect(cells, `${copy}: the gate row must exist`).not.toBe("");
    expect(/§2\.5|체인 핸드오프/.test(cells), `${copy}: the exempt case is chain handoff`).toBe(true);
    expect(
      /(?:T1|§5\.1)/.test(cells),
      `${copy}: stated only below the table, the re-arm does not reach the agent reading the gate SSOT`
    ).toBe(true);
    expect(/발동|적용된다|유지/.test(cells), `${copy}: the re-arm must be positive, not implied`).toBe(true);
  });

  it("AC-1 (discriminator): the exempt case and the re-armed case are told apart by a decidable test", () => {
    // The feasibility hop satisfies both descriptions at once — §2.5 fixes
    // `kiwi-srs-feasibility → kiwi-planner` (a chain hand-off) while Table T1 forks that same
    // transition to `kiwi-srs-research`. Naming the two cases is not enough; the row must say which
    // wins, or two agents on the same invocation disagree about whether a critical gate fired.
    const cells = rowCells(gatesOf(read(copy)), /multi-candidate-ambiguous/).join(" ");
    // NOT `/후보 ≥2/`: the row's own gate description has carried that phrase since before this
    // change, so matching it proves nothing — deleting the discriminator leaves it green. Both
    // halves of the actual test must appear: when the gate stands down, and when it still fires.
    expect(
      /유일하게 결정되면/.test(cells),
      `${copy}: the row must state the condition under which the gate stands down`
    ).toBe(true);
    expect(
      /둘 이상이면[^|]*발동/.test(cells),
      `${copy}: the discriminator must be the candidate count, not which section the hop came from`
    ).toBe(true);
  });

  it("AC-4 (single rule): every site that specifies the self-recursion test specifies the SAME one", () => {
    // Two independent disjunctions let the gate row satisfy its half with one rule name and §6.5
    // satisfy its half with a different one — both green while naming incompatible procedures, which
    // is how three live rules shipped. The token is now fixed and required identically everywhere,
    // and Table T1 and §10, which also re-infer from the event log, are included.
    const text = body(read(copy));
    // Two drafts of this rule were wrong in opposite directions. "Skip child events and look at the
    // previous own-skill event" finds one by construction, so the ERROR was vacuously true. "An empty
    // gap between two own-skill events" rested on a false premise — an advisory or `--stats` run also
    // emits an own-skill event with no children, so cycle → status check → cycle hard-errored. The
    // loop only exists when the skill spawns ITSELF; a user re-invoking it is not a loop.
    const RULE = /next_hint/;
    const AUTO = /자동 진행/;
    const sites: Array<[string, string]> = [
      ["§0.AG gate row", line(text, /self-recursive-spawn/)],
      ["§0.5", line(text, /§0\.5\s*\|/)],
      ["§6.5", section(text, /^#{3}\s*6\.5\s/)],
      ["Table T1 self row", line(text, /^\|\s*`?kiwi-pipeline`?\s*\|\s*TASK_DONE/)],
      ["§10", section(text, /^#{2}\s*10\.\s/)]
    ];
    for (const [where, chunk] of sites) {
      expect(chunk, `${copy}: ${where} must exist`).not.toBe("");
      expect(
        RULE.test(chunk),
        `${copy}: ${where} specifies a different self-recursion test — the discriminator is the previous own-skill event's next_hint`
      ).toBe(true);
      expect(
        AUTO.test(chunk),
        `${copy}: ${where} must distinguish an automatic re-entry from a user re-invocation, or an ordinary cycle → status → cycle sequence hard-errors`
      ).toBe(true);
    }
    // And the undefined window the first draft invented must not survive anywhere.
    expect(/run 창/.test(text), `${copy}: "run 창" is defined nowhere and no event field carries it`).toBe(false);
    // …and the backwards form must not come back: "skip the children and look at the previous
    // own-skill event" makes the ERROR condition vacuously true.
    expect(
      /자식 이벤트를 건너뛰/.test(text),
      `${copy}: that phrasing finds an own-skill event by construction, so the guard can never say no`
    ).toBe(false);
    expect(
      /사이에 자식 이벤트가 하나도 없으면/.test(text),
      `${copy}: an empty gap is also what an advisory or --stats run leaves, so it cannot be the discriminator`
    ).toBe(false);
  });

  it("AC-6: the start-candidate gate row carries its own scoping, not only §3's prose", () => {
    // The sibling gate's AC exists precisely because the gate TABLE is what an --auto agent reads;
    // a scoping stated only in the section below does not reach that reader. The same asymmetry had
    // been left in place here.
    const cells = rowCells(gatesOf(read(copy)), /pipeline-start-candidate-ambiguous/).join(" ");
    expect(cells, `${copy}: the start-candidate gate row must exist`).not.toBe("");
    expect(
      /작업 입력/.test(cells),
      `${copy}: an --auto agent reading only the gate table halts on every first run`
    ).toBe(true);
  });

  it("AC-5 (spawn mode): no rule below §0.2 still gates spawning on a flag", () => {
    const text = body(read(copy));
    const spawnMode = line(text, /외부 스킬 spawn 모드/);
    expect(spawnMode, `${copy}: §0.9 must exist`).not.toBe("");
    expect(
      /작업 입력/.test(spawnMode),
      `${copy}: the row that DEFINES the spawn mode names a trigger the default never supplies`
    ).toBe(true);
    // The §12 dependency row names a host-specific tool, so only the claude rendering has a
    // `Skill` 도구 row. What must hold everywhere is that no degradation note still describes the
    // loss as disabling one opt-in flag.
    expect(
      /`--run` 옵션 비활성/.test(text),
      `${copy}: losing the spawn tool now disables the default behaviour, not one opt-in flag`
    ).toBe(false);
  });

  it("AC-2: the gate_id string is unchanged", () => {
    expect(/multi-candidate-ambiguous/.test(gatesOf(read(copy))), `${copy}: closed gate-id enum`).toBe(true);
  });

  it("AC-3: the commit-auto-push refusal no longer keys on single-next-step recommendation", () => {
    const cycle = cycleOf(read(copy));
    const refusal = line(cycle, /kiwi-commit-auto-push[^\n]*잇지 않는다/);
    expect(refusal, `${copy}: the refusal that keeps an irreversible push out of the chain must exist`).not.toBe("");
    expect(
      /단일 다음-단계 추천에만 적용된다/.test(cycle),
      `${copy}: keyed on a mode the flip reduces to residual, this stops keeping push out of the chain`
    ).toBe(false);
    expect(HEDGE.test(refusal), `${copy}: the refusal must be absolute`).toBe(false);
    // The replacement must not overclaim either. §6.1 spawns a single clear candidate immediately
    // under `--auto --run`, so a T1 row reached after the chain ends can be taken without an
    // explicit user pick — claiming otherwise makes this sentence contradict §6.1 rather than bound it.
    expect(
      /사용자가 명시적으로 선택한 다음 단계로만/.test(refusal),
      `${copy}: §6.1 spawns a single clear candidate under --auto --run, so this claim would be false`
    ).toBe(false);
    expect(
      /스스로 잇는 홉이 아니다|체인이 잇지 않는다/.test(refusal),
      `${copy}: what the refusal owns is that the CHAIN does not add the hop`
    ).toBe(true);
  });

  it("AC-4: the self-recursion guard accounts for interleaved child events", () => {
    const guard = line(body(read(copy)), /self-recursive-spawn/);
    expect(guard, `${copy}: the guard row must exist`).not.toBe("");
    expect(
      /사이|중간|끼[어우]/.test(guard),
      `${copy}: a default cycle interleaves child events between re-entries, so an immediately-preceding test never trips`
    ).toBe(true);
  });

  // Enumerating the stale spellings one by one is how three CRITICAL ones shipped green: the list
  // named §0.7, §6.1 and §6.2 and missed §2, §2.5 and §6.6, which are the sections that DEFINE the
  // chain and bound its unattended completion. The check is now a sweep — every surviving mention
  // of the token must be one of the small set of places allowed to name it, and those places are
  // listed by what they say, not by where they are.
  it("AC-5: no statement anywhere is left conditioned on the cycle flag", () => {
    const text = body(read(copy));
    const ALLOWED = [
      /아무 동작도 바꾸지 않는다\(inert\)/, // the one inert declaration
      /기본값과 동일 — 아무것도 바꾸지 않는다/, // its §1.2 matrix row
      /진입 시점에 거부/, // the contradictory-combination refusal
      /인식되지 않는 철자/ // the --no-cycle guard
    ];
    const offenders = lines(text, /`--cycle`/).filter((l) => !ALLOWED.some((ok) => ok.test(l)));
    expect(
      offenders,
      `${copy}: these lines still key behaviour on a token that is now the default:\n${offenders.join("\n")}`
    ).toEqual([]);
  });
});

describe.each(PIPELINE_COPIES)("FR-FLOW-128 — no false safety claim survives (%s)", (copy) => {
  it("AC-1: §0.2 no longer claims the default mutates nothing, and names what it reaches", () => {
    const row = line(body(read(copy)), /§0\.2/);
    expect(row, `${copy}: the §0.2 row must exist`).not.toBe("");
    expect(
      /자기 mutation 금지 \(기본값\)/.test(row),
      `${copy}: the default is now the maximally-mutating path; this is a false claim on line 25`
    ).toBe(false);
    for (const reached of [/SRS/, /작업 트리|워킹 트리/, /status|상태/]) {
      expect(reached.test(row), `${copy}: §0.2 must name ${reached} as reached by the default`).toBe(true);
    }
  });

  it("AC-2: the §2.6 worktree exception survives the restatement", () => {
    expect(
      /§2\.6/.test(line(body(read(copy)), /§0\.2/)),
      `${copy}: FR-FLOW-027 AC-4 requires the worktree exception to stay stated in §0.2`
    ).toBe(true);
  });

  it("AC-3: the --auto-alone row is not conditioned on the cycle flag", () => {
    const row = line(matrixOf(read(copy)), /`--auto` 단독/);
    expect(row, `${copy}: the --auto-alone row must exist`).not.toBe("");
    expect(
      /`--cycle` 미지정/.test(row),
      `${copy}: conditioned on a clause the flip makes never true, --auto silently becomes an unattended full-chain run`
    ).toBe(false);
  });

  it("AC-4: §11's bare-invocation row names the cycle and says it spawns", () => {
    const cells = rowCells(examplesOf(read(copy)), /"[/$]kiwi-pipeline"/).join(" ");
    expect(cells, `${copy}: §11 must still carry a bare-invocation row`).not.toBe("");
    expect(/사이클/.test(cells), `${copy}: the bare call must name the cycle it now enters`).toBe(true);
    expect(
      /추천 출력/.test(cells),
      `${copy}: advisory-only is the pre-flip behaviour — §11 is the section a partial landing forgets`
    ).toBe(false);
    // The status phrasings the description advertises must not resolve, in §11, to an immediate
    // spawn. "위와 동일" inherits whatever row precedes it, which is how one of them came to point
    // at `--auto --run`.
    const nextRow = rowCells(examplesOf(read(copy)), /"kiwi 다음 뭐 해"/).join(" ");
    expect(nextRow, `${copy}: the natural-language status row must exist`).not.toBe("");
    expect(
      /--none-cycle|실행 없음/.test(nextRow),
      `${copy}: a status phrasing must not inherit an immediate-spawn row`
    ).toBe(true);
  });

  it("AC-5: §8.2's emit shape covers a run that executed the chain, stated once", () => {
    const emit = emitOf(read(copy));
    expect(
      /사이클|체인/.test(emit),
      `${copy}: a default run emits one event describing five stages, not a recommendation`
    ).toBe(true);
    // A duplicated paragraph is the signature of a botched edit and no other assertion sees it.
    expect(lines(emit, /기본 호출은 §2\.5 체인을 실행하므로/).length, `${copy}: stated exactly once`).toBe(1);
    // The prose instructs the writer to record which hop the cycle reached; the SHAPE below it must
    // have somewhere to put that, or the instruction has no field to land in.
    expect(
      /완주|마지막 홉/.test(emit) && /중단|게이트/.test(emit),
      `${copy}: the emitted summary/notes fields must name the hop reached and the halting gate`
    ).toBe(true);
  });

  it("AC-7: no claim above §0.2 still describes an advisory-only skill", () => {
    const text = body(read(copy));
    const head = text.split("## 0.")[0];
    expect(head, `${copy}: the body preamble must exist`).not.toBe("");
    expect(
      /사이클/.test(head),
      `${copy}: the responsibility list six lines under the corrected sentence still omits running the chain`
    ).toBe(true);
    expect(
      /\*read·다음 단계 추천\* 만 담당/.test(text),
      `${copy}: §0.1 still scopes the document to read-and-recommend`
    ).toBe(false);
  });

  it("AC-1 (start gate): the first-run start-candidate gate does not halt a chain whose first hop is fixed", () => {
    const phase0 = section(body(read(copy)), /^#{2}\s*3\.\s/);
    const gate = line(phase0, /시작 후보/);
    expect(gate, `${copy}: the start-candidate rule must exist`).not.toBe("");
    expect(
      /작업 입력/.test(phase0),
      `${copy}: with a work input §2.5 fixes the first hop to kiwi-srs, so "intent ambiguous" is false there`
    ).toBe(true);
  });

  it("AC-6 (target): §2.6 itself carries the work-input condition its pointer in §1.2 claims", () => {
    // Fixing the pointer and not the target is worse than fixing neither: the two sections agreed
    // before, and disagreeing now puts the skill's ONLY direct mutation (`git worktree add`) under
    // two rules. §2.6 is the section §1.2 defers to, so the condition has to be stated there.
    const six6 = section(body(read(copy)), /^#{2}\s*2\.6\s/);
    expect(six6, `${copy}: §2.6 must exist`).not.toBe("");
    expect(
      /작업 입력/.test(six6),
      `${copy}: §2.6 still creates a worktree on --wt alone, which §1.2 says it must not`
    ).toBe(true);
  });

  it("AC-6: --wt supplied alone is stated, consistently with the work-input rule", () => {
    const wt = line(body(read(copy)), /`--wt` 단독/);
    expect(wt, `${copy}: --wt alone is inert today and its meaning changes under the new default`).not.toBe("");
    // `--wt` is not in the closed work-input enumeration, so the line immediately above governs:
    // an argument-only invocation does not spawn. A --wt-alone line claiming the cycle runs and a
    // `git worktree add` fires contradicts it — and `git worktree add` is the skill's only direct
    // mutation, so the contradiction is over the one thing it is allowed to write itself.
    expect(
      /돌지 않는다|만들지 않는다|생성하지 않는다/.test(wt),
      `${copy}: --wt is not a work input, so --wt alone must not be described as running the cycle`
    ).toBe(true);
  });

  it("AC-1 (intro): the body's own one-line self-description does not gate spawning on --auto", () => {
    const intro = line(body(read(copy)), /직접 작업을 수행하지 않는다/);
    expect(intro, `${copy}: the third sentence of the body must exist`).not.toBe("");
    expect(
      /\(`--auto` 시\) 직접 spawn/.test(intro),
      `${copy}: spawning is now triggered by a work input with or without --auto, and this is the line an agent skims first`
    ).toBe(false);
  });

  it("AC-3 (§6.6): the unattended-completion section applies to the run it actually governs", () => {
    const six6 = section(body(read(copy)), /^#{3}\s*6\.6\s/);
    expect(six6, `${copy}: §6.6 must exist`).not.toBe("");
    expect(
      /`--cycle` \+ `--auto`/.test(six6),
      `${copy}: keyed on an inert token, the only clause bounding an unattended full-chain run never applies`
    ).toBe(false);
    expect(/작업 입력/.test(six6), `${copy}: §6.6 must key on the condition that actually starts the chain`).toBe(true);
  });
});

describe.each(ORCHESTRATOR_COPIES)("FR-FLOW-129 — orchestrator refusal re-keyed (%s)", (copy) => {
  const refusalLine = () => line(body(read(copy)), /이름으로 개별 호출한다/);

  it("AC-1: the refusal names the skill rather than the flag", () => {
    const refusal = refusalLine();
    expect(refusal, `${copy}: the per-wave delegation refusal must exist`).not.toBe("");
    expect(
      /`[/$]kiwi-pipeline --cycle` 로 진입하지 않는다/.test(refusal),
      `${copy}: once the flag is not what starts the chain, refusing the flag permits the bare call`
    ).toBe(false);
    expect(
      /어떤 호출 형태로도|호출하지 않는다/.test(refusal),
      `${copy}: the object of the refusal must be the skill`
    ).toBe(true);
  });

  it("AC-2: the refusal states that --none-cycle is not the remedy", () => {
    expect(
      /--none-cycle/.test(refusalLine()),
      `${copy}: a single-next-step advisor is not this rung's behaviour either`
    ).toBe(true);
  });

  it("AC-3: the recorded seam reason survives", () => {
    const refusal = refusalLine();
    expect(/derive-readiness/.test(refusal), `${copy}: the 3.c′ seam must survive`).toBe(true);
    expect(/commit-wave-inputs/.test(refusal), `${copy}: the 3.d seam must survive`).toBe(true);
  });

  it("AC-1 (gate subject): the wt-delegation gate it declares still has a subject", () => {
    // The file's own rule, three lines above its gate table: declaring a gate whose predicate cannot
    // occur is worse than omitting it, because the empty identifier still enters the cross-variant
    // parity assertion. Broadening the refusal to every invocation form removed the last delegation
    // a `kiwi-pipeline --wt` could arrive on, so the refusal must be scoped to what this rung does.
    // NOT `/wave 위임|wave 마다의 위임/`: the line has opened with `**wave 마다의 위임은 …**` since
    // before this change, so that disjunction is green on the very wording it was written to reject.
    // The scope has to be attached to the refusal clause itself, not merely present on the line.
    const refusal = refusalLine();
    expect(
      /이 rung 의 wave 위임은[^\n]*어떤 호출 형태로도/.test(refusal),
      `${copy}: the refusal must be scoped to wave delegation, or wt-delegation-refused has no possible subject`
    ).toBe(true);
  });
});

describe.each(CONTRACT_COPIES)("FR-FLOW-129 — the shared contract carries the default (%s)", (copy) => {
  it("AC-4: the cycle contract states the new default, in every rendering", () => {
    const text = read(copy);
    expect(
      /Under `--cycle`/.test(text),
      `${copy}: keyed on the flag, the shared SSOT contradicts the skill it governs`
    ).toBe(false);
    expect(/by default/i.test(text), `${copy}: the shared contract must state the default`).toBe(true);
    expect(/--none-cycle/.test(text), `${copy}: the shared contract must name the opt-out`).toBe(true);
  });

  it("AC-5: the status/stability row reflects the transitive effect of the default", () => {
    const cells = rowCells(read(copy), /kiwi-pipeline/).join(" ").toLowerCase();
    expect(cells, `${copy}: the capability row must exist`).not.toBe("");
    expect(
      /transitive|indirect|via/.test(cells),
      `${copy}: the default now updates status and stability through its children`
    ).toBe(true);
  });

  it("AC-7: the routing table's post-kiwi-pm hop is the one the chain actually takes", () => {
    // Once this file tells its reader the chain is the default, a routing row sending the hop after
    // `kiwi-pm` straight to an irreversible commit-and-push contradicts the skill's own refusal to
    // chain that hop. The claude copy was already correct; the others were not.
    // Selected by TASK_DONE: the Responsibilities table also carries a `kiwi-pm` row and comes first.
    const row = rowCells(read(copy), /`kiwi-pm`[^|]*\|[^|]*TASK_DONE/).join(" ");
    expect(row, `${copy}: the kiwi-pm routing row must exist`).not.toBe("");
    expect(
      /kiwi-review-fix-loop/.test(row),
      `${copy}: the chain's hop after kiwi-pm is the review loop, not an automatic push`
    ).toBe(true);
  });

  it("AC-4 (header): the header names the cycle among the reasons to load this contract", () => {
    const header = read(copy).split("## ")[0];
    expect(
      /cycle/i.test(header),
      `${copy}: the end-to-end cycle contract lives in this file and the header must say so`
    ).toBe(true);
  });
});

// A survival pin, not a driver: kiwi-wave-master is not modified by this change, and this block is
// green before and after it. It is here because the inert-token decision rests entirely on this
// caller continuing to work, so a later edit that drops `--run` from the wave call must fail loudly.
describe.each(WAVE_COPIES)("FR-FLOW-124 — the wave caller survives the inert token (%s)", (copy) => {
  it("the per-wave call still states execution explicitly", () => {
    const call = line(body(read(copy)), /[/$]kiwi-pipeline[^\n]*--from=feasibility/);
    expect(call, `${copy}: the per-wave skip-authoring call must survive`).not.toBe("");
    expect(
      /--run/.test(call),
      `${copy}: with the implicit run bound to a work input, the wave call must be explicit about executing`
    ).toBe(true);
  });
});
